name: Publish SDK Packages

on:
  push:
    branches: [main, feature-dev]
    tags: ['v*']
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        registry-url: 'https://npm.pkg.github.com'
        scope: '@ppyuesheng'
        
    - name: Setup pnpm
      uses: pnpm/action-setup@v2
      with:
        version: latest
        
    - name: Install dependencies
      run: pnpm install
      
    - name: Build packages
      run: pnpm run build
      
    - name: Update package versions
      run: |
        # 自动更新版本号，基于git commit数量
        VERSION="1.0.$(git rev-list --count HEAD)"
        echo "Setting version to $VERSION"
        
        # 更新所有包的版本号
        pnpm version $VERSION --workspace-root --no-git-tag-version
        find packages -name package.json -exec sed -i "s/\"version\": \".*\"/\"version\": \"$VERSION\"/" {} \;
        find packages -name package.json -exec sed -i "s/\"workspace:\*\"/\"$VERSION\"/" {} \;
        
    - name: Publish packages
      run: |
        # 发布所有包到GitHub Packages
        for pkg in packages/*/; do
          if [ -d "$pkg/dist" ]; then
            echo "Publishing $(basename $pkg)..."
            cd $pkg
            npm publish --access public --registry https://npm.pkg.github.com || echo "Package already exists or failed to publish"
            cd ../..
          fi
        done